region: ap-northeast-1
cluster: template
service: template
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 10m0s
plugins:
  - name: tfstate
    config:
      url: s3://okawa-tfstate/template/cicd/main.tfstate