name: deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    name: Deploay app to Fargate
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀start deploy ${{env.AWS_REGION}}"
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          # role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-duration-seconds: 1800